--CREATE AN EMPTY TABLE
CREATE TABLE IF NOT EXISTS PRODUCT(
PRO_ID TEXT PRIMARY KEY,
PRO_NAME TEXT,
PRO_PRICE INT,
PRO_COM TEXT
);

--INSERT VALUES INTO THE TABLE
INSERT INTO PRODUCT (PRO_ID, PRO_NAME, PRO_PRICE, PRO_COM) VALUES
("101", "MOTHER BOARD", 3200, "15"),
("102", "KEY BOARD", 450, "16"),
("103", "ZIP DRIVE", 250, "14"),
("104", "SPEAKER", 3550, "11"),
("105", "MONITOR", 5000, "12"),
("106", "DVD DRIVE", 900, "12"),
("107", "PRINTER", 2600, "13");

--MIN AND MAX
SELECT PRO_NAME, PRO_PRICE FROM PRODUCT
WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT);

SELECT PRO_NAME, PRO_PRICE FROM PRODUCT
WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT);

SELECT MIN(PRO_PRICE) AS SMALLEST_PRICE FROM PRODUCT;

--OR
SELECT * FROM PRODUCT
WHERE PRO_NAME = "PRINTER" OR PRO_ID = '101';

--AND
SELECT * FROM PRODUCT
WHERE PRO_NAME = "PRINTER" AND PRO_ID = '107';

--UPDATE A ROW
UPDATE PRODUCT
SET PRO_COM = "12"
WHERE PRO_NAME = "SPEAKER";

SELECT * FROM PRODUCT;

--DELETE A ROW
DELETE FROM PRODUCT
WHERE PRO_ID = "102";

SELECT * FROM PRODUCT;
