--GROUP BY
SELECT COUNT(CITY) AS "CITY COUNT" , CITY FROM supplier 
GROUP BY CITY;

--ORDER BY
SELECT * FROM supplier 
ORDER BY CITY;

UPDATE supplier
SET STATUS=5
WHERE SNO = "S1";
SELECT * FROM supplier;

SELECT * FROM supplier 
ORDER BY STATUS DESC, CITY ASC; -- PRIORITY WILL BE GIVEN TO STATUS
